import Header from './components/Header'
import SideBar from './components/SideBar'
import './globals.css'
import { Roboto_Mono } from 'next/font/google'

const roboto = Roboto_Mono({
  weight: ['400', '700'],
  subsets: ['latin'] 
})

export const metadata = {
  title: 'Mainstack App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="container">
          <SideBar />
          <div className="main-container">
            <Header />
            {children}
          </div>
        </div>
        
      </body>
    </html>
  )
}
